### ISSUE TITLE
GOOD rating. What interval value will be assigned ?  

### ISSUE THREAD

**Issue by dedu6ka** [p4nix/add-card-do-first-review#1]
I  can see only one **usage case**: the cards which need an unusually large ivl.  
How will it work? Can I assign the interval using an interactive window ( like the "Rememorize.." add-on does ?

Normal interval cards.
 They should be IMO reviewed  / tested after a specified Delay; this 'Initial' delay should be the 3rd Learning Step value; the 2nd step could be used to 'pre-learn' cards. 

FWIW: AnKingMed delays reviewing for 20 min. 

Thanks for sharing the add-0n.

**Comment by p4nix** [comment]
Hello @dedu6ka ,

the add-on is pretty simple. I do not know if it will be of use to others. It will add a button to the add-on menu with the title "Add+Review", which is connected with a shortcut (default: Ctrl+Shift+Return). If you activate the button (or shortcut), it will instantly do the review of the card at the same time (ease = 3 on new scheduler, Good). There is no interactive window, although this could be interesting to look into. Not very high priority for my kind of workflow though, to be completely honest.

I've written this add-on because I believe that "adding" a card is just like the first review. I use this add-on together with decks which have learning step: 50, graduate: 5d. I do not have a goldfish brain. Coherent knowledge derived from incremental reading should last at least those 5 days. So using this add-on will instantly send those items to their 5 day graduation intervals. If you'd use it with something like learning step: 1 10, it will send those cards to the interval of 10 min.

Inspiration has been gotten from Supermemo, where a lot of people have disabled "Final Drill", a function which lets you review all newly added cards/wrong cards for the day. If you actually understand and pay attention to the material you are adding (and if it is coherent), the learning queue (or Final Drill in SM) is a waste of time.

I understand that assigning custom schedules with a dialog could be interesting, but not the highest priority for me personally right now. Feel free to share your thoughts if you disagree with my philosophy, I'm always interested to hear about different workflows and ideas.

**Comment by p4nix** [comment]
Oh, and I also find it helpful for quickly introducing supplementary cards (mnemonics, connections, etc) into decks which have too many new cards for those supplementary cards to arrive quick enough in the learn queue.

**Comment by dedu6ka** [comment]
Error: 
When loading '⁨Add Card Do First Review⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 208, in loadAddons
  File "C:\Users\Vit\AppData\Roaming\Anki2\addons21\1394953283\__init__.py", line 79, in <module>
    gui_hooks.add_cards_did_init.append(extend_add_cards)
AttributeError: module 'aqt.gui_hooks' has no attribute 'add_cards_did_init'
⁩--- End of error.
PS. Thanks for the tip to use the spare profile. Was able to delete the add-on without problems.

**Comment by p4nix** [comment]
@dedu6ka Can you please tell me your version of Anki, so maybe I can have a look into this or at least adjust the version my add-on is compatible to? I am new to Anki development and I don't know when this hook was introduced.

EDIT:
Ah yeah, this change was only introduced in 2.1.24. Thanks for reporting to me, so I will adjust the compatible versions and actually try out on 2.1.24 :) Isn't too high on my priority list to fix this, but maybe sometime later.

**Comment by dedu6ka** [comment]
Strange, because my version is  
Version 2.1.22 (0ecc189a)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1 

No rush, i am just testing it.
